language: node_js
node_js:
  - 'stable'
  - '7.0'
  - '6.0'
  - '5.0'
  - '4.0'
# Handle git submodules yourself
git:
  submodules: false
# Use sed to replace the SSH URL with the public URL, then initialize submodules
before_install:
  - sed -i 's/git@github.com:/https:\/\/github.com\//' .gitmodules
#  - git submodule update --init --recursive
script:
  - npm run build
  - npm run coveralls
